import { User, Checklist, ChartData, Chat, Message, Report, Role } from './api';

export const mockUsers: User[] = [
  {
    id: 1,
    username: "ivan_ivanov",
    full_name: "Иван Иванов",
    role: "супер админ",
    telegram_id: "@ivan_ivanov",
    created_at: "2024-01-10T10:00:00Z",
  },
  {
    id: 2,
    username: "maria_petrova",
    full_name: "Мария Петрова",
    role: "админ",
    telegram_id: "@maria_petrova",
    created_at: "2024-01-12T14:30:00Z",
  },
  {
    id: 3,
    username: "petr_sidorov",
    full_name: "Петр Сидоров",
    role: "менеджмент",
    telegram_id: "@petr_sidorov",
    created_at: "2024-01-08T09:15:00Z",
  },
  {
    id: 4,
    username: "anna_kozlova",
    full_name: "Анна Козлова",
    role: "начальник отдела 1",
    telegram_id: "@anna_kozlova",
    created_at: "2024-01-15T11:20:00Z",
  },
  {
    id: 5,
    username: "sergey_volkov",
    full_name: "Сергей Волков",
    role: "начальник отдела 2",
    telegram_id: "@sergey_volkov",
    created_at: "2024-01-20T16:45:00Z",
  },
  {
    id: 6,
    username: "elena_smirnova",
    full_name: "Елена Смирнова",
    role: "проверяющий",
    telegram_id: "@elena_smirnova",
    created_at: "2024-01-18T13:00:00Z",
  },
];

export const mockChecklists: Checklist[] = [
  {
    id: 1,
    title: "Проверка оборудования цеха №1",
    description: "Ежедневная проверка основного оборудования производственного цеха",
    items: [
      {
        id: 1,
        text: "Проверить работу станка А",
        completed: false,
        description: "Убедиться, что станок работает без вибраций",
      },
      {
        id: 2,
        text: "Проверить уровень масла",
        completed: false,
        description: "Проверить уровень масла в редукторе",
      },
      {
        id: 3,
        text: "Осмотреть ремни и шкивы",
        completed: false,
        description: "Проверить состояние ремней на износ",
      },
      {
        id: 4,
        text: "Проверить систему охлаждения",
        completed: false,
        description: "Убедиться, что система охлаждения работает",
      },
      {
        id: 5,
        text: "Проверить давление в системе",
        completed: false,
        description: "Проверить показания манометров",
      },
      {
        id: 6,
        text: "Проверить работу датчиков",
        completed: false,
        description: "Убедиться, что все датчики работают корректно",
      },
    ],
    status: "Не начато",
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2024-01-15T08:00:00Z",
  },
  {
    id: 2,
    title: "Проверка безопасности",
    description: "Еженедельная проверка систем безопасности",
    items: [
      {
        id: 1,
        text: "Проверить пожарную сигнализацию",
        completed: false,
        description: "Протестировать все датчики дыма",
      },
      {
        id: 2,
        text: "Проверить огнетушители",
        completed: false,
        description: "Убедиться, что огнетушители на месте и не просрочены",
      },
      {
        id: 3,
        text: "Проверить аварийные выходы",
        completed: false,
        description: "Убедиться, что выходы не заблокированы",
      },
      {
        id: 4,
        text: "Проверить систему вентиляции",
        completed: false,
        description: "Убедиться, что вентиляция работает исправно",
      },
      {
        id: 5,
        text: "Проверить освещение аварийных путей",
        completed: false,
        description: "Проверить работу аварийного освещения",
      },
      {
        id: 6,
        text: "Проверить наличие аптечек",
        completed: false,
        description: "Убедиться, что аптечки на месте и укомплектованы",
      },
    ],
    status: "Не начато",
    created_at: "2024-01-10T09:00:00Z",
    updated_at: "2024-01-10T09:00:00Z",
  },
  {
    id: 3,
    title: "Проверка качества продукции",
    description: "Контроль качества готовой продукции",
    items: [
      {
        id: 1,
        text: "Проверить размеры изделий",
        completed: false,
        description: "Измерить размеры выборочной партии",
      },
      {
        id: 2,
        text: "Проверить поверхность на дефекты",
        completed: false,
        description: "Визуальный осмотр поверхности",
      },
      {
        id: 3,
        text: "Проверить упаковку",
        completed: false,
        description: "Убедиться, что упаковка соответствует стандартам",
      },
      {
        id: 4,
        text: "Проверить маркировку",
        completed: false,
        description: "Проверить наличие и правильность маркировки",
      },
      {
        id: 5,
        text: "Проверить вес изделий",
        completed: false,
        description: "Проверить соответствие веса техническим требованиям",
      },
      {
        id: 6,
        text: "Записать результаты",
        completed: false,
        description: "Внести результаты проверки в журнал",
      },
    ],
    status: "Не начато",
    created_at: "2024-01-12T10:00:00Z",
    updated_at: "2024-01-12T10:00:00Z",
  },
  {
    id: 4,
    title: "Техническое обслуживание",
    description: "Ежемесячное техническое обслуживание оборудования",
    items: [
      {
        id: 1,
        text: "Замена фильтров",
        completed: false,
        description: "Заменить воздушные и масляные фильтры",
      },
      {
        id: 2,
        text: "Смазка подшипников",
        completed: false,
        description: "Проверить и смазать все подшипники",
      },
      {
        id: 3,
        text: "Проверка электрических соединений",
        completed: false,
        description: "Проверить все электрические соединения на надежность",
      },
      {
        id: 4,
        text: "Калибровка датчиков",
        completed: false,
        description: "Проверить и откалибровать все датчики",
      },
      {
        id: 5,
        text: "Очистка оборудования",
        completed: false,
        description: "Очистить оборудование от пыли и загрязнений",
      },
      {
        id: 6,
        text: "Проверка документации",
        completed: false,
        description: "Обновить журнал технического обслуживания",
      },
    ],
    status: "Не начато",
    created_at: "2024-01-08T07:00:00Z",
    updated_at: "2024-01-08T07:00:00Z",
  },
];

export const mockChartDataWeek: ChartData[] = [
  { date: "2024-01-15", value: 4, label: "Пн" },
  { date: "2024-01-16", value: 5, label: "Вт" },
  { date: "2024-01-17", value: 3, label: "Ср" },
  { date: "2024-01-18", value: 6, label: "Чт" },
  { date: "2024-01-19", value: 4, label: "Пт" },
  { date: "2024-01-20", value: 2, label: "Сб" },
  { date: "2024-01-21", value: 3, label: "Вс" },
];

export const mockChartDataMonth: ChartData[] = [
  { date: "2024-01-01", value: 5, label: "Неделя 1" },
  { date: "2024-01-08", value: 6, label: "Неделя 2" },
  { date: "2024-01-15", value: 4, label: "Неделя 3" },
  { date: "2024-01-22", value: 5, label: "Неделя 4" },
];

export const mockChartDataYear: ChartData[] = [
  { date: "2024-01", value: 5, label: "Янв" },
  { date: "2024-02", value: 6, label: "Фев" },
  { date: "2024-03", value: 4, label: "Мар" },
  { date: "2024-04", value: 5, label: "Апр" },
  { date: "2024-05", value: 6, label: "Май" },
  { date: "2024-06", value: 4, label: "Июн" },
  { date: "2024-07", value: 5, label: "Июл" },
  { date: "2024-08", value: 6, label: "Авг" },
  { date: "2024-09", value: 4, label: "Сен" },
  { date: "2024-10", value: 5, label: "Окт" },
  { date: "2024-11", value: 6, label: "Ноя" },
  { date: "2024-12", value: 4, label: "Дек" },
];

export const mockMessages: Message[] = [
  {
    id: 1,
    chat_id: 1,
    sender_id: 1,
    text: "Привет! Как дела?",
    created_at: "2024-01-22T10:00:00Z",
  },
  {
    id: 2,
    chat_id: 1,
    sender_id: 2,
    text: "Привет! Всё отлично, спасибо!",
    created_at: "2024-01-22T10:05:00Z",
  },
  {
    id: 3,
    chat_id: 1,
    sender_id: 1,
    text: "Отлично! Можешь помочь с проверкой оборудования?",
    created_at: "2024-01-22T10:10:00Z",
  },
  {
    id: 4,
    chat_id: 2,
    sender_id: 3,
    text: "Добрый день! Нужна помощь с чеклистом",
    created_at: "2024-01-22T11:00:00Z",
  },
  {
    id: 5,
    chat_id: 2,
    sender_id: 1,
    text: "Конечно, чем могу помочь?",
    created_at: "2024-01-22T11:05:00Z",
  },
  {
    id: 6,
    chat_id: 3,
    sender_id: 4,
    text: "Здравствуйте! Когда будет готов отчёт?",
    created_at: "2024-01-22T12:00:00Z",
  },
  {
    id: 7,
    chat_id: 3,
    sender_id: 1,
    text: "Отчёт будет готов к концу недели",
    created_at: "2024-01-22T12:15:00Z",
  },
];

export const mockChats: Chat[] = [
  {
    id: 1,
    user1_id: 1,
    user2_id: 2,
    last_message: mockMessages[2],
    unread_count: 0,
    created_at: "2024-01-20T09:00:00Z",
    updated_at: "2024-01-22T10:10:00Z",
  },
  {
    id: 2,
    user1_id: 1,
    user2_id: 3,
    last_message: mockMessages[4],
    unread_count: 1,
    created_at: "2024-01-21T10:00:00Z",
    updated_at: "2024-01-22T11:05:00Z",
  },
  {
    id: 3,
    user1_id: 1,
    user2_id: 4,
    last_message: mockMessages[6],
    unread_count: 0,
    created_at: "2024-01-19T08:00:00Z",
    updated_at: "2024-01-22T12:15:00Z",
  },
  {
    id: 4,
    user1_id: 1,
    user2_id: 5,
    last_message: undefined,
    unread_count: 0,
    created_at: "2024-01-18T14:00:00Z",
    updated_at: "2024-01-18T14:00:00Z",
  },
];

export const mockReports: Report[] = [
  {
    id: 1,
    date: "2024-01-22",
    inspector_id: 1,
    checklist_id: 1,
    department_index: 0,
    items: [
      {
        id: 1,
        checklist_item_id: 1,
        text: "Проверить работу станка А",
        completed: true,
        description: "Убедиться, что станок работает без вибраций",
      },
      {
        id: 2,
        checklist_item_id: 2,
        text: "Проверить уровень масла",
        completed: true,
        description: "Проверить уровень масла в редукторе",
      },
      {
        id: 3,
        checklist_item_id: 3,
        text: "Осмотреть ремни и шкивы",
        completed: false,
        description: "Проверить состояние ремней на износ",
      },
      {
        id: 4,
        checklist_item_id: 4,
        text: "Проверить систему охлаждения",
        completed: true,
        description: "Убедиться, что система охлаждения работает",
      },
    ],
    status: "В процессе",
    score: 3,
    created_at: "2024-01-22T08:00:00Z",
    updated_at: "2024-01-22T10:30:00Z",
  },
  {
    id: 2,
    date: "2024-01-22",
    inspector_id: 2,
    checklist_id: 2,
    department_index: 1,
    items: [
      {
        id: 1,
        checklist_item_id: 1,
        text: "Проверить пожарную сигнализацию",
        completed: true,
        description: "Протестировать все датчики дыма",
      },
      {
        id: 2,
        checklist_item_id: 2,
        text: "Проверить огнетушители",
        completed: true,
        description: "Убедиться, что огнетушители на месте и не просрочены",
      },
      {
        id: 3,
        checklist_item_id: 3,
        text: "Проверить аварийные выходы",
        completed: true,
        description: "Убедиться, что выходы не заблокированы",
      },
    ],
    status: "Завершено",
    score: 3,
    created_at: "2024-01-22T09:00:00Z",
    updated_at: "2024-01-22T11:00:00Z",
  },
  {
    id: 3,
    date: "2024-01-21",
    inspector_id: 3,
    checklist_id: 3,
    department_index: 0,
    items: [
      {
        id: 1,
        checklist_item_id: 1,
        text: "Проверить размеры изделий",
        completed: true,
        description: "Измерить размеры выборочной партии",
      },
      {
        id: 2,
        checklist_item_id: 2,
        text: "Проверить поверхность на дефекты",
        completed: true,
        description: "Визуальный осмотр поверхности",
      },
      {
        id: 3,
        checklist_item_id: 3,
        text: "Проверить упаковку",
        completed: false,
        description: "Убедиться, что упаковка соответствует стандартам",
      },
      {
        id: 4,
        checklist_item_id: 4,
        text: "Проверить маркировку",
        completed: true,
        description: "Проверить наличие и правильность маркировки",
      },
      {
        id: 5,
        checklist_item_id: 5,
        text: "Записать результаты",
        completed: false,
        description: "Внести результаты проверки в журнал",
      },
    ],
    status: "В процессе",
    score: 3,
    created_at: "2024-01-21T10:00:00Z",
    updated_at: "2024-01-21T14:20:00Z",
  },
  {
    id: 4,
    date: "2024-01-20",
    inspector_id: 1,
    checklist_id: 4,
    department_index: 1,
    items: [
      {
        id: 1,
        checklist_item_id: 1,
        text: "Замена фильтров",
        completed: true,
        description: "Заменить воздушные и масляные фильтры",
      },
      {
        id: 2,
        checklist_item_id: 2,
        text: "Смазка подшипников",
        completed: true,
        description: "Проверить и смазать все подшипники",
      },
      {
        id: 3,
        checklist_item_id: 3,
        text: "Проверка электрических соединений",
        completed: true,
        description: "Проверить все электрические соединения на надежность",
      },
      {
        id: 4,
        checklist_item_id: 4,
        text: "Калибровка датчиков",
        completed: true,
        description: "Проверить и откалибровать все датчики",
      },
      {
        id: 5,
        checklist_item_id: 5,
        text: "Очистка оборудования",
        completed: true,
        description: "Очистить оборудование от пыли и загрязнений",
      },
      {
        id: 6,
        checklist_item_id: 6,
        text: "Проверка документации",
        completed: true,
        description: "Обновить журнал технического обслуживания",
      },
    ],
    status: "Завершено",
    score: 6,
    created_at: "2024-01-20T07:00:00Z",
    updated_at: "2024-01-20T15:00:00Z",
  },
  {
    id: 5,
    date: "2024-01-19",
    inspector_id: 4,
    checklist_id: 1,
    department_index: 0,
    items: [
      {
        id: 1,
        checklist_item_id: 1,
        text: "Проверить работу станка А",
        completed: true,
        description: "Убедиться, что станок работает без вибраций",
      },
      {
        id: 2,
        checklist_item_id: 2,
        text: "Проверить уровень масла",
        completed: true,
        description: "Проверить уровень масла в редукторе",
      },
      {
        id: 3,
        checklist_item_id: 3,
        text: "Осмотреть ремни и шкивы",
        completed: true,
        description: "Проверить состояние ремней на износ",
      },
      {
        id: 4,
        checklist_item_id: 4,
        text: "Проверить систему охлаждения",
        completed: true,
        description: "Убедиться, что система охлаждения работает",
      },
    ],
    status: "Завершено",
    score: 4,
    created_at: "2024-01-19T08:00:00Z",
    updated_at: "2024-01-19T09:30:00Z",
  },
  {
    id: 6,
    date: "2024-01-18",
    inspector_id: 5,
    checklist_id: 2,
    department_index: 1,
    items: [
      {
        id: 1,
        checklist_item_id: 1,
        text: "Проверить пожарную сигнализацию",
        completed: true,
        description: "Протестировать все датчики дыма",
      },
      {
        id: 2,
        checklist_item_id: 2,
        text: "Проверить огнетушители",
        completed: true,
        description: "Убедиться, что огнетушители на месте и не просрочены",
      },
      {
        id: 3,
        checklist_item_id: 3,
        text: "Проверить аварийные выходы",
        completed: true,
        description: "Убедиться, что выходы не заблокированы",
      },
    ],
    status: "Завершено",
    score: 3,
    created_at: "2024-01-18T09:00:00Z",
    updated_at: "2024-01-18T10:15:00Z",
  },
];

export const mockRoles: Role[] = [
  { id: 1, name: "менеджмент", type: "role", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: 2, name: "админ", type: "role", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: 3, name: "супер админ", type: "role", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: 4, name: "начальник отдела 1", type: "role", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: 5, name: "начальник отдела 2", type: "role", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: 6, name: "проверяющий", type: "role", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: 7, name: "Отдел 1", type: "department", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: 8, name: "Отдел 2", type: "department", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: 9, name: "Отдел 3", type: "department", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
];
